package my.ADR;

import static my.ADR.LoadItem.username;
import static my.ADR.LoadItem.password;
import static my.ADR.SerialIO.cfmMessage;
import static my.ADR.SerialIO.opPhone;
import static my.ADR.LoadItem.url;

public class Arrival extends javax.swing.JPanel {
    
    public Arrival() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloLabel = new javax.swing.JLabel();
        deliverLabel = new javax.swing.JLabel();
        items = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helloLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 56)); // NOI18N
        helloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloLabel.setText("Hello!");
        add(helloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 30, -1, -1));

        deliverLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 44)); // NOI18N
        deliverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliverLabel.setText("Here is your delivery");
        deliverLabel.setPreferredSize(new java.awt.Dimension(500, 75));
        add(deliverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 115, -1, -1));

        items.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        items.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        items.setText("Retrieve items");
        items.setPreferredSize(new java.awt.Dimension(500, 75));
        items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itemsMouseReleased(evt);
            }
        });
        add(items, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 500, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void itemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsMousePressed

    private void itemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseReleased
        if(!items.getText().equals("Items retrieved"))
        {
            MainFrame.arrivalPanel.setVisible(false);
            MainFrame.passcodePanel.setVisible(true);
        }
        else
        {
            MainFrame.arrivalPanel.setVisible(false);
            MainFrame.ratingPanel.setVisible(true);
            
            cfmMessage = "Guest at Room " + MainFrame.entryPanel.room + " has retrieved the items. Returning to base";
            //MainFrame.sms.SendSMS(username, password, cfmMessage, opPhone, url);
        }
    }//GEN-LAST:event_itemsMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel deliverLabel;
    public javax.swing.JLabel helloLabel;
    public javax.swing.JLabel items;
    // End of variables declaration//GEN-END:variables
}
