/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ADR;

public class Delivery extends javax.swing.JPanel {

    public Delivery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliverLabel = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliverLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 44)); // NOI18N
        deliverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliverLabel.setText("I'm making a delivery");
        deliverLabel.setPreferredSize(new java.awt.Dimension(500, 75));
        add(deliverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
   
    /* FOR DEBUGGING PURPOSE ONLY*/
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        MainFrame.deliveryPanel.setVisible(false);
        MainFrame.arrivalPanel.setVisible(true);
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliverLabel;
    // End of variables declaration//GEN-END:variables
}
