package my.ADR;

public class Details extends javax.swing.JPanel {

    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 56)); // NOI18N
        detailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailsLabel.setText("Autonomous Delivery Robot");
        detailsLabel.setPreferredSize(new java.awt.Dimension(700, 75));
        add(detailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        infoLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 40)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Info...");
        infoLabel.setPreferredSize(new java.awt.Dimension(600, 75));
        add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, -1, -1));

        ok.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        ok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ok.setText("ok");
        ok.setMaximumSize(new java.awt.Dimension(100, 100));
        ok.setMinimumSize(new java.awt.Dimension(30, 30));
        ok.setPreferredSize(new java.awt.Dimension(75, 75));
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okMouseReleased(evt);
            }
        });
        add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void okMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_okMousePressed

    private void okMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseReleased
        MainFrame.detailsPanel.setVisible(false);
        MainFrame.startPanel.setVisible(true);
    }//GEN-LAST:event_okMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel ok;
    // End of variables declaration//GEN-END:variables
}
