package my.ADR;

import java.util.*;

public class LoadItem extends javax.swing.JPanel {
    Random rndmNmbr = new Random();
    StringBuilder pcHolder = new StringBuilder();
    
    public static final String username = "JAMD";
    public static final String password = "JAMDrobot";
    private String message;
    public static final String url = "http://usa.bulksms.com/eapi/submission/send_sms/2/2.0";
    
    public int[] passCode = new int[4];
    String pc;  // Passcode as String
    
    String hexCheck = "-?[0-9A-F]+";
    String alphaCheck = "-?[A-F]+";
    String numCheck = "-?[0-9]+";
    private int tempVal;
    public  byte[] roomVal = new byte[2];

    public LoadItem() {
        initComponents();
    }
    
    private void roomToByte()
    {
        int temp_room = Integer.parseInt(MainFrame.entryPanel.room.substring(1));
        String temp_str;
        
        if(temp_room < 16)
            temp_str = "0" + Integer.toHexString(temp_room).toUpperCase();
        else
            temp_str = Integer.toHexString(temp_room).toUpperCase();

        String[] str = new String[temp_str.length()];
        
        int[] nib = new int[2];
        
        if(temp_str.length() == 2 && temp_str.matches(hexCheck))
        {
            for(int i = 0; i < str.length; i++)
            {
                str[i] = temp_str.substring(i,i+1);

                if(str[i].matches(numCheck))
                    nib[i] = str[i].charAt(0) - '0';
                else if(str[i].matches(alphaCheck))
                    nib[i] = str[i].charAt(0) - '7';
            }
        }
        
        tempVal = ((nib[0] << 4) | nib[1]) << 8;
        
        roomVal[0] = (byte) ((tempVal >> 8) & 0xFF);
        roomVal[1] = (byte) 0x00;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        go = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();
        loadLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        go.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        go.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        go.setText("Go!");
        go.setPreferredSize(new java.awt.Dimension(75, 75));
        go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goMouseReleased(evt);
            }
        });
        add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        back.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("back");
        back.setPreferredSize(new java.awt.Dimension(75, 75));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backMouseReleased(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        cancel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("cancel");
        cancel.setPreferredSize(new java.awt.Dimension(75, 75));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseReleased(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        msgLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 48)); // NOI18N
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLabel.setText("<html><center>Please load items for room...</center></html>");
        msgLabel.setOpaque(true);
        msgLabel.setPreferredSize(new java.awt.Dimension(670, 65));
        add(msgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 370, 130));
        add(loadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 50, 310, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void goMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_goMousePressed

    private void goMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goMouseReleased
        MainFrame.entryPanel.phone = "1" + MainFrame.entryPanel.phone;
        
        for(int i = 0; i < 4; i++)
        {
            passCode[i] = rndmNmbr.nextInt(9) + 1;
            pcHolder.append(passCode[i]);
        }
        
        pc = pcHolder.toString();   // Passcode as String
        message = "Hello! Your delivery is on its way. Your passkey is " + pc;
        
        roomToByte();
        MainFrame.serial.transmit(roomVal);   // 1st TX - Give main Arduino room #
        
        System.out.println(message);
        //MainFrame.sms.SendSMS(username, password, message, MainFrame.entryPanel.phone, url);
        
        MainFrame.loadPanel.setVisible(false);
        MainFrame.deliveryPanel.setVisible(true);
    }//GEN-LAST:event_goMouseReleased

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_backMousePressed

    private void backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseReleased
        MainFrame.entryPanel.entryCount--;
        MainFrame.entryPanel.chCount = 4;
        
        MainFrame.entryPanel.msgLabel.setText("<html><center>Please enter your room number:</center></html>");   // Ask for room #
        MainFrame.entryPanel.answrLabel.setText(MainFrame.entryPanel.room);
        
        MainFrame.entryPanel.enter.setEnabled(true);
        
        MainFrame.loadPanel.setVisible(false);
        MainFrame.entryPanel.setVisible(true);        
    }//GEN-LAST:event_backMouseReleased

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMousePressed

    private void cancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseReleased
        MainFrame.entryPanel.entryCount = 0;
        MainFrame.entryPanel.chCount = 0;
        
        Arrays.fill(MainFrame.entryPanel.phoneNumber, 0, 10, '\0');
        Arrays.fill(MainFrame.entryPanel.roomNumber, 0, 4, '\0');
        MainFrame.entryPanel.phone = "";
        MainFrame.entryPanel.room = "";
        
        MainFrame.entryPanel.back.setText("cancel");     // Reset
        MainFrame.entryPanel.msgLabel.setText("<html><center>Please enter your phone number:</center></html>");   // Reset
        MainFrame.entryPanel.answrLabel.setText("");
        
        MainFrame.entryPanel.cancel.setVisible(false);   // Reset
        MainFrame.entryPanel.cancel.setEnabled(false);   // Reset
        MainFrame.entryPanel.enter.setEnabled(false);
        MainFrame.entryPanel.delete.setEnabled(false);
        
        MainFrame.loadPanel.setVisible(false);
        MainFrame.startPanel.setVisible(true);
    }//GEN-LAST:event_cancelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel go;
    private javax.swing.JLabel loadLabel;
    private javax.swing.JLabel msgLabel;
    // End of variables declaration//GEN-END:variables
}
