package my.ADR;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import com.teknikindustries.bulksms.SMS;

public class MainFrame extends JFrame {
    public static SerialIO serial = new SerialIO();
    public static SMS sms = new SMS();
    
    public MainFrame() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Images/Icon.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new my.ADR.Start();
        entryPanel = new my.ADR.Entry();
        loadPanel = new my.ADR.LoadItem();
        deliveryPanel = new my.ADR.Delivery();
        arrivalPanel = new my.ADR.Arrival();
        passcodePanel = new my.ADR.Passcode();
        ratingPanel = new my.ADR.Rating();
        returnPanel = new my.ADR.Return();
        settingsPanel = new my.ADR.Settings();
        detailsPanel = new my.ADR.Details();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autonomous Deliviery Robot");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Nirmala UI Semilight", 0, 48)); // NOI18N
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(242, 242, 242));
        mainPanel.setVerifyInputWhenFocusTarget(false);
        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(startPanel, "card2");
        mainPanel.add(entryPanel, "card3");
        mainPanel.add(loadPanel, "card4");
        mainPanel.add(deliveryPanel, "card5");
        mainPanel.add(arrivalPanel, "card6");
        mainPanel.add(passcodePanel, "card7");
        mainPanel.add(ratingPanel, "card8");
        mainPanel.add(returnPanel, "card9");
        mainPanel.add(settingsPanel, "card10");
        mainPanel.add(detailsPanel, "card11");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        setSize(new java.awt.Dimension(800, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            serial.close();
            System.exit(0);
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try{Thread.sleep(2500);} catch(InterruptedException e) {}
            new MainFrame().setVisible(true);
        });
        
        serial.initialize();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static my.ADR.Arrival arrivalPanel;
    public static my.ADR.Delivery deliveryPanel;
    public static my.ADR.Details detailsPanel;
    public static my.ADR.Entry entryPanel;
    public static my.ADR.LoadItem loadPanel;
    public static javax.swing.JPanel mainPanel;
    public static my.ADR.Passcode passcodePanel;
    public static my.ADR.Rating ratingPanel;
    public static my.ADR.Return returnPanel;
    public static my.ADR.Settings settingsPanel;
    public static my.ADR.Start startPanel;
    // End of variables declaration//GEN-END:variables
}
