/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ADR;

/**
 *
 * @author Damon
 */
public class Rating extends javax.swing.JPanel {
    public byte[] homeVal = new byte[2];
    /**
     * Creates new form Rating
     */
    public Rating() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingLabel = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ratingLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 56)); // NOI18N
        ratingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratingLabel.setText("How was this experience?");
        add(ratingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 30, 650, 75));

        star1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        star1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star1.setText("1");
        star1.setPreferredSize(new java.awt.Dimension(100, 100));
        star1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                star1MouseReleased(evt);
            }
        });
        add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 125, -1, -1));

        star2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        star2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star2.setText("2");
        star2.setPreferredSize(new java.awt.Dimension(100, 100));
        star2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                star2MouseReleased(evt);
            }
        });
        add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 125, -1, -1));

        star3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        star3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star3.setText("3");
        star3.setPreferredSize(new java.awt.Dimension(100, 100));
        star3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                star3MouseReleased(evt);
            }
        });
        add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 125, -1, -1));

        star4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        star4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star4.setText("4");
        star4.setPreferredSize(new java.awt.Dimension(100, 100));
        star4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                star4MouseReleased(evt);
            }
        });
        add(star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 125, -1, -1));

        star5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        star5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star5.setText("5");
        star5.setPreferredSize(new java.awt.Dimension(100, 100));
        star5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                star5MouseReleased(evt);
            }
        });
        add(star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 125, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void star1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseReleased
        homeVal[0] = (byte) 0x20;
        homeVal[1] = (byte) 0x00;
        MainFrame.serial.transmit(homeVal);
        
        MainFrame.ratingPanel.setVisible(false);
        MainFrame.returnPanel.setVisible(true);
    }//GEN-LAST:event_star1MouseReleased

    private void star2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseReleased
        homeVal[0] = (byte) 0x20;
        homeVal[1] = (byte) 0x00;
        MainFrame.serial.transmit(homeVal);
        
        MainFrame.ratingPanel.setVisible(false);
        MainFrame.returnPanel.setVisible(true);
    }//GEN-LAST:event_star2MouseReleased

    private void star3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseReleased
        homeVal[0] = (byte) 0x20;
        homeVal[1] = (byte) 0x00;
        MainFrame.serial.transmit(homeVal);
        
        MainFrame.ratingPanel.setVisible(false);
        MainFrame.returnPanel.setVisible(true);
    }//GEN-LAST:event_star3MouseReleased

    private void star4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseReleased
        homeVal[0] = (byte) 0x20;
        homeVal[1] = (byte) 0x00;
        MainFrame.serial.transmit(homeVal);
        
        MainFrame.ratingPanel.setVisible(false);
        MainFrame.returnPanel.setVisible(true);
    }//GEN-LAST:event_star4MouseReleased

    private void star5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseReleased
        homeVal[0] = (byte) 0x20;
        homeVal[1] = (byte) 0x00;
        MainFrame.serial.transmit(homeVal);
        
        MainFrame.ratingPanel.setVisible(false);
        MainFrame.returnPanel.setVisible(true);
    }//GEN-LAST:event_star5MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}
