/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ADR;

import java.util.Arrays;

/**
 *
 * @author Damon
 */
public class Return extends javax.swing.JPanel {

    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        byeLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 480));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        byeLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 56)); // NOI18N
        byeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        byeLabel.setText("Bye!");
        add(byeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 30, 650, 75));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        MainFrame.entryPanel.entryCount = 0;
        MainFrame.entryPanel.chCount = 0;
        
        /**** Entry Panel Reset ****/
        Arrays.fill(MainFrame.entryPanel.phoneNumber, 0, 10, '\0');
        Arrays.fill(MainFrame.entryPanel.roomNumber, 0, 4, '\0');
        MainFrame.entryPanel.phone = "";
        MainFrame.entryPanel.room = "";
        
        MainFrame.entryPanel.answrLabel.setText("");
        MainFrame.entryPanel.enter.setEnabled(false);
        MainFrame.entryPanel.delete.setEnabled(false);
        
        MainFrame.entryPanel.msgLabel.setText("<html><center>Please enter your phone number:</center></html>");   // Reset
        MainFrame.entryPanel.back.setText("cancel");     // Reset
        MainFrame.entryPanel.cancel.setVisible(false);   // Reset
        MainFrame.entryPanel.cancel.setEnabled(false);   // Reset
        
        /**** LoadItem Panel Reset ****/
        MainFrame.loadPanel.pcHolder.delete(0, 4);
        Arrays.fill(MainFrame.loadPanel.passCode, 0, 4, '\0');
        MainFrame.loadPanel.pc = "";
        
        /**** Pass code Panel Reset ****/
        MainFrame.passcodePanel.pcCount = 0;
            
        Arrays.fill(MainFrame.passcodePanel.userPC, 0, 4, '\0');
        MainFrame.passcodePanel.userPasscode = "";

        MainFrame.passcodePanel.answrLabel.setText("");
        MainFrame.passcodePanel.enter.setEnabled(false);
        MainFrame.passcodePanel.delete.setEnabled(false);
        
        /**** Arrival Panel Reset ****/
        MainFrame.arrivalPanel.items.setText("Retrieve items");
        
        MainFrame.returnPanel.setVisible(false);
        MainFrame.startPanel.setVisible(true);
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel byeLabel;
    // End of variables declaration//GEN-END:variables
}
