package my.ADR;

public class Start extends javax.swing.JPanel {

    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloLabel = new javax.swing.JLabel();
        whatLabel = new javax.swing.JLabel();
        deliverLabel = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helloLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 56)); // NOI18N
        helloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloLabel.setText("Hello!");
        add(helloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 30, -1, -1));

        whatLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 32)); // NOI18N
        whatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whatLabel.setText("What can I do?");
        whatLabel.setPreferredSize(new java.awt.Dimension(235, 50));
        whatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                whatLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                whatLabelMouseReleased(evt);
            }
        });
        add(whatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 400, -1, -1));

        deliverLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 40)); // NOI18N
        deliverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliverLabel.setText("I'm ready to start a delivery.");
        deliverLabel.setPreferredSize(new java.awt.Dimension(500, 75));
        deliverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deliverLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deliverLabelMouseReleased(evt);
            }
        });
        add(deliverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 115, -1, -1));

        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/ADR/Images/SettingsIcon.png"))); // NOI18N
        settingsLabel.setPreferredSize(new java.awt.Dimension(80, 80));
        settingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                settingsLabelMouseReleased(evt);
            }
        });
        add(settingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deliverLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliverLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverLabelMousePressed

    private void deliverLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliverLabelMouseReleased
        MainFrame.startPanel.setVisible(false);
        MainFrame.entryPanel.setVisible(true);
    }//GEN-LAST:event_deliverLabelMouseReleased

    private void whatLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whatLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_whatLabelMousePressed

    private void whatLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whatLabelMouseReleased
        MainFrame.startPanel.setVisible(false);
        MainFrame.detailsPanel.setVisible(true);
    }//GEN-LAST:event_whatLabelMouseReleased

    private void settingsLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsLabelMousePressed

    private void settingsLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsLabelMouseReleased
        MainFrame.startPanel.setVisible(false);
        MainFrame.settingsPanel.setVisible(true);
    }//GEN-LAST:event_settingsLabelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliverLabel;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JLabel whatLabel;
    // End of variables declaration//GEN-END:variables
}
